name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          DEBUG: ${{ secrets.DEBUG }}
          ORIGIN_WHITELIST: ${{ secrets.ORIGIN_WHITELIST }}
          SERVICES: ${{ secrets.SERVICES }}
          API_KEY: ${{ secrets.API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
